//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientDoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientDoc()
        {
            this.DonneesCIN = new HashSet<DonneesCIN>();
        }
    
        public string IdClient { get; set; }
        public string CodeCSP { get; set; }
        public string CodeDoc { get; set; }
        public int IdDoc { get; set; }
        public string UrlDoc { get; set; }
    
        public virtual CSP CSP { get; set; }
        public virtual Documents Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonneesCIN> DonneesCIN { get; set; }
    }   
}
