//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSP_DOC
    {
        public int Id { get; set; }
        public string CodeCSP { get; set; }
        public string CodeDoc { get; set; }
        public string C5 { get; set; }
        public string C6 { get; set; }
        public Nullable<int> C7 { get; set; }
    
        public virtual CSP CSP { get; set; }
        public virtual Documents Documents { get; set; }
    }
}
