//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Documents()
        {   
            this.CSP_DOC = new HashSet<CSP_DOC>();
            this.Donnees = new HashSet<Donnees>();
            this.ClientDoc = new HashSet<ClientDoc>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Libelle { get; set; }
        public string Type { get; set; }
        public string Origine { get; set; }
        public string CodeEmetteur { get; set; }
        public string Filler { get; set; }
        public string C8 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSP_DOC> CSP_DOC { get; set; }
        public virtual Emetteurs Emetteurs { get; set; }
        public virtual TypeDoc TypeDoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donnees> Donnees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientDoc> ClientDoc { get; set; }
    }
}
