//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonneesCIN
    {
        public int Id { get; set; }
        public int IdDoc { get; set; }
        public string NOCIN { get; set; }
        public string NOM { get; set; }
        public string PERNOM { get; set; }
        public Nullable<System.DateTime> DTNAISS { get; set; }
        public Nullable<System.DateTime> DTVALID { get; set; }
        public string ADRESS { get; set; }
        public string ADRESS2 { get; set; }
        public string VILLE { get; set; }
        public string PPERE { get; set; }
        public string NMERE { get; set; }
        public string Dossier { get; set; }
        public string Link { get; set; }
    
        public virtual Documents Documents { get; set; }
        
        public virtual ClientDoc ClientDoc { get; set; }
    }
       
}
