//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donnees
    {
        public int Id { get; set; }
        public string Code_CSP { get; set; }
        public string CodeDoc { get; set; }
        public string CodeData { get; set; }
        public string LibData { get; set; }
        public string TypeData { get; set; }
        public string C7 { get; set; }
        public string C8 { get; set; }
    
        public virtual CSP CSP { get; set; }
        public virtual Documents Documents { get; set; }
    }
}
