//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matrix.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MatrixEntities : DbContext
    {
        public MatrixEntities()
            : base("name=MatrixEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CSP> CSP { get; set; }
        public virtual DbSet<CSP_DOC> CSP_DOC { get; set; }
        public virtual DbSet<Documents> Documents { get; set; }
        public virtual DbSet<Donnees> Donnees { get; set; }
        public virtual DbSet<Emetteurs> Emetteurs { get; set; }
        public virtual DbSet<TypeDoc> TypeDoc { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ClientDoc> ClientDoc { get; set; }
        public virtual DbSet<DonneesCIN> DonneesCIN { get; set; }
        
        public virtual PanelModel PanelModel { get; set; }
    }

}
